#!/bin/bash

# sourced by bash

# I know #!/bin/bash isn't needed, but it makes joe highlighting the syntax.

set -e

if [ $(id -u) != 0 ]; then
	echo "Hey, you gotta be root!" >&2
	exit 1
fi

export LC_ALL=en_US.UTF-8
export LANG=C
unset  LANGUAGE
export lang="$(<language)"

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

unset SORTDIR_LOCALE
unset SORTDIR_VERSCMP
unset SORTDIR_REVERSE

modprobe loop >/dev/null 2>&1 || true

#loopdev="$(losetup -f)"
loopdev="/dev/loop0"

WORKDIR="$PWD/Work"
ROOTDIR="$WORKDIR/root"
TMPDIR="$WORKDIR/tmp"
DVDDIR="$WORKDIR/DVD"
ISODIR="$PWD/ISO"
ISODATE=$(date '+%F')
#ISODATE=$(date '+%Y.%m.%d')

IMG_NAME="uhulinux.img"
ROIMG_NAME="uhulinux.roimg"
IMG="$WORKDIR/$IMG_NAME"
ROIMG="$WORKDIR/$ROIMG_NAME"

PACKAGES_ALL="$WORKDIR"/packages_all.txt
PACKAGES_CD="$WORKDIR"/packages_cd.txt

if [[ -f UHU_RELEASE ]]; then
	UHU_RELEASE="UHU-Linux $(<UHU_RELEASE) ${DESKTOP^^}"
	UHU_RELEASE_FULL="UHU-Linux $(<UHU_RELEASE)-${DESKTOP^^}-${ISODATE//-}"
else
	echo "Hiányzik a release fájl!"
fi

cdlabel="$UHU_RELEASE_FULL"
cdlabel_boot="${cdlabel// /_}"
release_file="${cdlabel// /-}"

APT_STATEDIR_LIVE="/var/lib/apt"
APT_CACHEDIR_LIVE="/var/cache/apt"
DPKG_STATEDIR_LIVE="/var/lib/dpkg"

APT_STATEDIR="apt/lib"
APT_CACHEDIR="apt/cache"
DPKG_STATEDIR="dpkg/lib"

if [ -n "${CDGEN_APT_SOURCES:-}" ]; then
	apt_sourcelist="-o Dir::Etc::SourceList=$CDGEN_APT_SOURCES"
else
	apt_sourcelist=""
fi
if [ -n "${CDGEN_APT_PREFERENCES:-}" ]; then
	apt_preferences="-o Dir::Etc::Preferences=$CDGEN_APT_PREFERENCES"
else
	apt_preferences=""
fi

apt_statedir="-o Dir::State=$WORKDIR/$APT_STATEDIR"
apt_cachedir="-o Dir::Cache=$WORKDIR/$APT_CACHEDIR"
apt_options="$apt_sourcelist $apt_preferences $apt_statedir $apt_cachedir"

echo -e "  \\e[1m${0##*/} ...\\e[0m"

mkdir -p "$ROOTDIR"
