#!/bin/bash -eu

. 00-common

for i in 1 2 3; do
	umount    "$ROOTDIR/dev"	2>/dev/null || true
	umount -d "$ROOTDIR/mnt"	2>/dev/null || true
	umount    "$ROOTDIR/proc"	2>/dev/null || true
	umount    "$ROOTDIR/sys"	2>/dev/null || true
	umount    "$ROOTDIR/tmp"	2>/dev/null || true
	umount -d "$ROOTDIR"	2>/dev/null || true
done

grep "$ROOTDIR" /proc/mounts && exit 1
rmdir "$ROOTDIR"

rm -f "$IMG"
rm -f "$ROIMG"
rm -f "$PACKAGES_ALL"
rm -f "$PACKAGES_CD"
rm -f "$WORKDIR"/installed_packages.txt
rm -f "$WORKDIR"/*.{iso,md5,sha}
rm -rf --one-file-system "$DVDDIR"
