#!/bin/bash -eu

. 00-common

# image size in dd format
case $DESKTOP in
	gnome)
		SIZE="7100M"
		;;
	mate)
		SIZE="6800M"
		;;
	*)
		SIZE="6400M"
esac

dd if=/dev/zero of="$IMG" bs=1 seek="$SIZE" count=0

losetup "$loopdev" "$IMG"
mkfs.ext4 -E resize=4294967295 -O uninit_bg,^has_journal "$loopdev"
tune2fs -i0 -c0 -m2 -LUHU "$loopdev"
mkdir -p "$ROOTDIR"
mount "$loopdev" "$ROOTDIR"
mkdir -p "$TMPDIR"
mkdir -p "$ROOTDIR/tmp"
mount --bind "$TMPDIR" "$ROOTDIR/tmp"
