#!/bin/bash -eu

. 00-common

#
# Initialize dpkg and apt-get.
#

mkdir -p "$ROOTDIR$DPKG_STATEDIR"/{info,updates}
touch "$ROOTDIR$DPKG_STATEDIR"/{available,status}
mkdir -p "$ROOTDIR$APT_STATEDIR"/lists/partial
mkdir -p "$ROOTDIR$APT_CACHEDIR"/archives/partial

apt-get \
	$apt_options \
	-o Debug::NoLocking="true" \
	update
