#!/bin/bash -eu

. 00-common

if [[ $DESKTOP = "rescue" ]]; then
	chroot "$ROOTDIR" useradd -m "$USER"
	chroot "$ROOTDIR" passwd -d "$USER"
	chroot "$ROOTDIR" passwd -d root
else
	chroot "$ROOTDIR" useradd -m uhu
	chroot "$ROOTDIR" passwd -d uhu
	chroot "$ROOTDIR" passwd -d root
fi

# gdm autologin
if [ -s "$ROOTDIR"/etc/gdm/custom.conf ]; then
	if [[ $DESKTOP = "rescue" ]]; then
		sed -ri -e '/^\s*AutomaticLogin/d' -e 's/\[daemon\]/[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin='$USER'/' "$ROOTDIR"/etc/gdm/custom.conf
	else
		sed -ri -e '/^\s*AutomaticLogin/d' -e 's/\[daemon\]/[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=uhu/' "$ROOTDIR"/etc/gdm/custom.conf
	fi
fi

# lightdm autologin
if [ -s "$ROOTDIR"/etc/lightdm/lightdm.conf ]; then
	if [[ $DESKTOP = "rescue" ]]; then
		sed -i -e 's/#pam-service=lightdm/pam-service=lightdm-autologin/' "$ROOTDIR"/etc/lightdm/lightdm.conf
		sed -i -e 's/#autologin-user=/autologin-user="$USER"/' "$ROOTDIR"/etc/lightdm/lightdm.conf
		sed -i -e 's/#autologin-in-background=false/autologin-in-background=true/' "$ROOTDIR"/etc/lightdm/lightdm.conf
	else
		sed -i -e 's/#pam-service=lightdm/pam-service=lightdm-autologin/' "$ROOTDIR"/etc/lightdm/lightdm.conf
		sed -i -e 's/#autologin-user=/autologin-user=uhu/' "$ROOTDIR"/etc/lightdm/lightdm.conf
		sed -i -e 's/#autologin-in-background=false/autologin-in-background=true/' "$ROOTDIR"/etc/lightdm/lightdm.conf
	fi
fi
