#!/bin/bash -eu

. 00-common

#
# Build a minimal chroot where some critical utilities
# (grub, rsync, mkisofs, mksquashfs, trunc, cdtest, cksfv...) will run.
#

# glibc 2.4 needs a mounted /proc for the *at() system calls
# if the running kernel does not directly support these calls.
# Well, it seems that it's not needed since coreutils 5.96,
# but it cannot hurt.
trap "umount $ROOTDIR/proc" EXIT
mkdir -p "$ROOTDIR/proc"
mount --bind /proc "$ROOTDIR/proc"

apt-get \
	$apt_options \
	-o Dir::State::status="$DPKG_STATEDIR/status" \
	-o Apt::Immediate-Configure="false" \
	-o DPkg::Options::=--root="$ROOTDIR" \
	-o Debug::NoLocking="true" \
	-o PackageManager::Configure="smart" \
	--yes \
	install $(cat packages_cd.txt)

chroot "$ROOTDIR" /sbin/uhu-pkg postinst +
chroot "$ROOTDIR" dpkg-query -W -f='${Package} ${Version}\n' \* > "$BASEDIR"/installed_packages_$DESKTOP.txt

touch "$ROOTDIR"/etc/fstab

# hostname beállítás
if [ ! -f "$ROOTDIR"/etc/hostname ]; then
	echo "localhost" > "$ROOTDIR"/etc/hostname
fi
