#!/bin/bash -eu

. 00-common

# add uhu-installer icon to desktop
# ~/Asztal szebb lenne, de kell egy xdg-user-dirs-update --set DESKTOP $HOME/Asztal
if [ -f "$ROOTDIR"/usr/share/applications/uhu-installer.desktop ]; then
	mkdir -p "$ROOTDIR"/home/uhu/Desktop
	cp "$ROOTDIR"/usr/share/applications/uhu-installer.desktop "$ROOTDIR"/home/uhu/Desktop/uhu-installer.desktop

	chmod 755 "$ROOTDIR"/home/uhu/Desktop/uhu-installer.desktop
else
	echo "uhu-installer.desktop missing"
fi

# default user settings
case $DESKTOP in
	gnome)
		echo 'gsettings set org.gnome.desktop.background show-desktop-icons true' >> "$ROOTDIR"/home/uhu/.profile
		echo 'gsettings set org.gnome.shell enabled-extensions "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"' >> "$ROOTDIR"/home/uhu/.profile
		;;
	mate)
		;;
	xfce)
		;;
	*)
		;;
esac

chown 1000.999 -R "$ROOTDIR"/home/uhu
