#!/bin/bash -eux

. 00-common

# add uhu-installer icon to desktop
if [ -f "$ROOTDIR"/usr/share/applications/uhu-installer.desktop ]; then
	mkdir -p "$ROOTDIR"/home/uhu/Asztal
	cp "$ROOTDIR"/usr/share/applications/uhu-installer.desktop "$ROOTDIR"/home/uhu/Asztal/uhu-installer.desktop

	chmod 755 "$ROOTDIR"/home/uhu/Asztal/uhu-installer.desktop
else
	echo "uhu-installer.desktop missing"
fi

chown 1000.999 -R "$ROOTDIR"/home/uhu
