#!/bin/bash -eu

. 00-common

# add uhu-installer icon to desktop
echo "Add uhu-installer icon to desktop"
chroot "$ROOTDIR" xdg-user-dirs-update

if [ -f "$ROOTDIR"/usr/share/applications/uhu-installer.desktop ]; then
	mkdir -p "$ROOTDIR"/home/uhu/Asztal
	cp "$ROOTDIR"/usr/share/applications/uhu-installer.desktop "$ROOTDIR"/home/uhu/Asztal/uhu-installer.desktop

	chmod 755 "$ROOTDIR"/home/uhu/Asztal/uhu-installer.desktop
else
	echo "uhu-installer.desktop missing"
fi

# default user settings
echo "Set default user settings"
case $DESKTOP in
	gnome)
		echo 'gsettings set org.gnome.desktop.background show-desktop-icons true' >> "$ROOTDIR"/home/uhu/.profile
		echo 'gsettings set org.gnome.shell enabled-extensions "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"' >> "$ROOTDIR"/home/uhu/.profile
		;;
	lxqt)
		mkdir -p "$ROOTDIR"/home/uhu/.config/lxqt/
		for config in lxqt panel session windowmanagers; do
			cp "$ROOTDIR"/etc/xdg/lxqt/${config}.conf "$ROOTDIR"/home/uhu/.config/lxqt/
		done
		;;
	xfce)
		mkdir -p "$ROOTDIR"/home/uhu/.config/xfce4/xfconf/xfce-perchannel-xml
		# default panel
		cp "$ROOTDIR"/etc/xdg/xfce4/panel/default.xml "$ROOTDIR"/home/uhu/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
		# default theme, icontheme
		cp "$ROOTDIR"/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml "$ROOTDIR"/home/uhu/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
		;;
	*)
		;;
esac

if [[ $DESKTOP = "rescue" ]]; then
	chown 1000.999 -R "$ROOTDIR"/home/"$USER"
else
	chown 1000.999 -R "$ROOTDIR"/home/uhu
fi
