#!/bin/bash -eu

. 00-common

# mappagyártás
mkdir -p "$DVDDIR"/{efi/boot,boot}

# grub téma a starfield témából
cp -r $DATADIR/grub $DVDDIR/boot/grub
# uhu grub háttérkép
background=uhu-grub-bg-dark.png
if [ -f $ROOTDIR/usr/share/backgrounds/UHU/ubk3.png ];then
background=ubk3.png
fi
cp -f $ROOTDIR/usr/share/backgrounds/UHU/$background $DVDDIR/boot/grub/themes/uhu/background.png
# grub font
cp $ROOTDIR/usr/share/grub/unicode.pf2 $DVDDIR/boot/grub/
# grub-pc fájlok
cp $ROOTDIR/usr/lib/grub/i386-pc/* $DVDDIR/boot/grub/i386-pc/

# bootolható fájlok
cp -a "$ROOTDIR/boot/memtest.bin" "$DVDDIR/memtest"

if [ "$mode" == "64" ]; then
	if [ -L "$ROOTDIR"/boot/kernel.x86_64 ]; then
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/kernel.x86_64) "$DVDDIR"/kernel
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/initrd.x86_64.gz) "$DVDDIR"/initrd
	else
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/bzImage.x86_64) "$DVDDIR"/kernel
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/initramfs.x86_64.cpio.gz) "$DVDDIR"/initrd
	fi
	platform="x86_64-efi"
	efigrub_img="bootx64.efi"
else
	if [ -L "$ROOTDIR"/boot/kernel.i386 ]; then
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/kernel.i386) "$DVDDIR"/kernel
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/initrd.i386.gz) "$DVDDIR"/initrd
	else
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/bzImage.i386) "$DVDDIR"/kernel
		cp "$ROOTDIR"/boot/$(readlink "$ROOTDIR"/boot/initramfs.i386.cpio.gz) "$DVDDIR"/initrd
	fi
    platform="i386-efi"
    efigrub_img="bootia32.efi"
fi

# efi grub fájlok
mkdir -p $DVDDIR/boot/grub/${platform}
cp $ROOTDIR/usr/lib/grub/${platform}/* $DVDDIR/boot/grub/${platform}/

# grub i386-pc core image
chroot $ROOTDIR \
	grub-mkimage \
	-d /usr/lib/grub/i386-pc \
	-o /tmp/core.img \
	-O i386-pc \
	-p /boot/grub \
	biosdisk \
	iso9660

# cdboot és core image összefűzése az El Torito -nek legacy boothoz
cat $ROOTDIR/usr/lib/grub/i386-pc/cdboot.img \
	$ROOTDIR/tmp/core.img >$DVDDIR/boot/grub/i386-pc/legacyeltorito.img

# tisztítás
rm $ROOTDIR/tmp/core.img

# efi boot

echo "Building ${efigrub_img}"

chroot $ROOTDIR \
	grub-mkimage \
	-d /usr/lib/grub/${platform} \
	-o /tmp/${efigrub_img} \
	-O ${platform} \
	-p /boot/grub \
	iso9660

cp $ROOTDIR/tmp/${efigrub_img} $DVDDIR/efi/boot/

MOUNTPOINT=$(mktemp -d)

# efieltorito.img gyártása
truncate -s 4M $DVDDIR/efieltorito.img
mkfs.fat -n MISO_EFI $DVDDIR/efieltorito.img &>/dev/null
mount -o loop $DVDDIR/efieltorito.img "${MOUNTPOINT}"
mkdir -p "${MOUNTPOINT}"/efi/boot
mv $ROOTDIR/tmp/${efigrub_img} ${MOUNTPOINT}/efi/boot/
umount ${MOUNTPOINT}
rmdir ${MOUNTPOINT}
