#!/bin/bash -eu

. 00-common

# copy img
cp -al "$ROIMG" "$DVDDIR/$IMG_NAME"
cd "$DVDDIR/"
md5sum -b "$IMG_NAME" > "$DVDDIR/md5sum"
# sha256sum -b "$IMG_NAME" > "$DVDDIR/shasum"
cd -

echo "Creating ISO image..."

if [ -d "$DVDDIR/boot" ]; then
	cat <<-END >"$DVDDIR/sortfile"
		/boot/grub/stage2_eltorito 903
		/boot/grub/boot.catalog 902
		/boot/grub/menu.lst 901
		/boot/grub 900
		/boot/isolinux/isolinux.bin 803
		/boot/isolinux/boot.catalog 802
		/boot/isolinux/isolinux.cfg 801
		/boot/isolinux 800
		/boot/themes/uhu-installer 701
		/boot/themes 700
		/boot/memtest 501
		/boot/bzImage 402
		/boot/initrd 401
		/boot 400
		/autorun.inf 391
		/uhu.ico 390
		/medium.txt 381
		/discdate.txt 380
		/Release 373
		/Packages 372
		/Packages.gz 371
		/Contents.gz 370
		/dostools 360
		/doc 350
	END
	if [ -d "$DVDDIR/boot/grub" ]; then
		bootoptions="-b boot/grub/stage2_eltorito -c boot/grub/boot.catalog"
	else
		bootoptions="-b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat"
	fi
	bootoptions="$bootoptions -no-emul-boot -boot-load-size 4 -boot-info-table"
	bootoptions="$bootoptions -sort "$DVDDIR"/sortfile"
else
	bootoptions=""
fi

mkdir -p "$ISODIR"

ISODEBUG=1 \
#chroot "$DVDDIR" \
mkisofs \
	-o "$ISODIR/$release_file.iso" \
	-A "UHU-Linux DVD Generator" \
	-V "$cdlabel" \
	-publisher "UHU-Linux Baráti Kör" \
	-p "UHU-Linux DVD Generator" \
	-J -T -hide-joliet-trans-tbl \
	-allow-limited-size \
	-r -hide-rr-moved \
	-input-charset UTF-8 \
	$bootoptions \
	"$DVDDIR"

isohybrid "$ISODIR/$release_file.iso"
sync

echo -n "Calculating checksums..."
cd "$ISODIR"
md5sum -b "$release_file.iso" > "$ISODIR/$release_file.md5" &
sha256sum -b "$release_file.iso" > "$ISODIR/$release_file.sha" &

cd -

wait
echo "ISO done..."
echo "ALL done... :)"

# umount image
umount    "$ROOTDIR/proc"	2>/dev/null || true
umount    "$ROOTDIR/sys"	2>/dev/null || true
umount    "$ROOTDIR/dev"	2>/dev/null || true
umount    "$ROOTDIR/tmp"	2>/dev/null || true
umount -d "$ROOTDIR/mnt"	2>/dev/null || true
umount -d "$ROOTDIR"		2>/dev/null || true
