#!/bin/bash -eu

. 00-common

# apt cache tisztítása
apt-get \
	$apt_options \
	-o Dir::State::status="$DPKG_STATEDIR/status" \
	autoclean

cd "$BASEDIR"

# minden más tisztítása
rm -rf --one-file-system "$DVDDIR"
rm -rf "$ROOTDIR"
rm -rf "$TMPDIR"
rm -rf "$WORKDIR"

