#!/bin/bash -e

. 00-common

case $1 in
	gnome)
		export DESKTOP=gnome
		export DESKTOPNAME=GNOME
		;;
	cinnamon)
		export DESKTOP=cinnamon
		export DESKTOPNAME=Cinnamon
		;;
	mate)
		export DESKTOP=mate
		export DESKTOPNAME=MATE
		;;
	xfce)
		export DESKTOP=xfce
		export DESKTOPNAME=XFCE
		;;
	kde)
		export DESKTOP=kde
		export DESKTOPNAME=KDE
		;;
	lxqt)
		export DESKTOP=lxqt
		export DESKTOPNAME=LXQt
		;;
	rescue)
		export DESKTOP=rescue
		export DESKTOPNAME=rescue

		if [ -n "$2" ]; then
		USER="$2"
		else
		USER="uhu"
		fi

		if [ -n "$3" ]; then
		rm -f UHU_RELEASE
		echo "$3" > UHU_RELEASE
		else
		cp /etc/uhu-release UHU_RELEASE
		fi

		if [ -f rescue.txt ]; then
			rm -f rescue.txt
		fi

		dpkg-query -W -f='${Package} ${Status}\n' | grep installed | sort -u | cut -f1 -d \ > rescue.txt
		echo "uhu-installer" >> rescue.txt
		echo "bootloader-theme-uhu-installer" >> rescue.txt
		;;
	--help|*)
		printf '\e[0;31m		Használat: ./cdgen gnome|cinnamon|mate|xfce|kde|lxqt|rescue [user] [UHU_RELEASE tartalma]
		Jelenleg csak ezekre készít iso-t.

		A rescue választása a futtató gépen telepített rendszerről készít bootolható
		telepítő iso fájlt.
		Ebben az esetben opcionálisan további paraméterek adhatók meg szóközzel elválasztva,
		úgymint a telepített rendszer valamely felhasználójának neve és az UHU_RELEASE fájl
		kívánt tartalma. Ez utóbbi nem tartalmazhat szóközt, vagy ha igen akkor kötelező
		idézőjelbe tenni!
		Ha nincs felhasználó megadva, akkor az automatikusan uhu lesz, az UHU_RELEASE
		tartalmára nincs megadva semmi akkor automatikusan az /etc/uhu-release fájl
		tartalma helyettesítődik be.

		Rescue módban ha a gépen olyan program/csomag van telepítve amely(ek) nem található(k)
		meg az /etc/apt/sources.list fájlban meghatározott csomagtárolókban akkor ebbe
		fájlba fel kel venni azokat a tárolókat ahol ezek a programok/csomagok megtalálhatók.
		Ellenkező esetben a program kiírja mely csomagok hiányoznak éa a futása hibaüzenettel
		leáll.


		Fájlok: (a data alkönyvtárban)
		packages.cd.orig.txt: az uhu svn-ben lévő cdgen csomaglistája
		packages.cd.base.txt: közös csomaglista, amit minden desktopnál használunk
		packages.gnome.txt: GNOME 3 csomaglista; kiegészíti a packages.cd.base.txt listáját
		packages.cinnamon.txt: Cinnamon csomaglista; kiegészíti a packages.cd.base.txt listáját
		packages.mate.txt: MATE csomaglista; kiegészíti a packages.cd.base.txt listáját
		packages.xfce.txt: XFCE csomaglista; kiegészíti a packages.cd.base.txt listáját
		packages.kde.txt: KDE 5 csomaglista; kiegészíti a packages.cd.base.txt listáját
		packages.lxqt.txt: LXQT csomaglista; kiegészíti a packages.cd.base.txt listáját
		sources.list: saját sources.list az apt-hoz, az /etc/apt alá kerül sources.list-cdgen néven

		Az iso neve (és az isolinux menüjének címe is) az UHU_RELEASE fájl tartalma lesz,
		kiegészítve a desktop nevével és az aktuális dátummal, az "UHU-Linux" stringhez fűzve.
		Így ha az UHU_RELEASE tartalma "3 UBK" (idézőjelek nélkül),
		akkor a címke UHU-Linux 3 UBK-MATE-20151018, az iso neve UHU-Linux-3-UBK-MATE-20151018.iso lesz.\n'
		exit
		;;
esac

mkdir -p $WORKDIR

if [ -f packages_cd.txt ]; then
	rm -f packages_cd.txt
fi

if [ -f rescue.txt ]; then
	mv rescue.txt packages_cd.txt
else
	cp "$DATADIR"/packages.cd.base.txt $BASEDIR/packages_cd.txt
	cat "$DATADIR"/packages.$DESKTOP.txt >> $BASEDIR/packages_cd.txt
fi

for i in [0-9][0-9]-*; do
	if [ -x "$i" ]; then
		case "$i" in
		  *~|*.orig|*.rej|*.skip)
			;;
		  *)
			"./$i"
			;;
		esac
	fi
done
